name: Linux


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
    statuses: write
    contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: remove admin req from shell script
      run: chmod +x linux.sh
      
    #- name: remove admin req from premake script
    #  run: chmod +x premake5
      
    #- name: install libx11-dev
    #  run: sudo apt install xorg-dev
    
    - name: build
      run: ./linux.sh
    - name: list files
      run: ls
