name: Windows

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  ## 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    #- name: Restore NuGet packages
    #  working-directory: ${{env.GITHUB_WORKSPACE}}/projects/VS2022
    #  run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: .\windows.bat 
    - name: list files
      run: cd "_bin/Release" && ls
    - name: Release artifact
      uses: actions/upload-artifact@v2
      with: 
          name: build
          path: "_bin/Release"  
